'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import QRCode from 'qrcode';
import {Zap,Link2,Send,Download,Monitor,History,Settings,ArrowUpRight,Copy,UploadCloud,X,Check,ShieldCheck,FileText,ImageIcon,Wifi,Clock,ArrowRight,LogOut,Search,ChevronRight} from 'lucide-react';
import style from './relay.module.css';
import {decode,encode,LIMIT,type Payload} from '../crypto';
import {useTransfer} from './use-transfer';
import {labels,statuses,size,scanPayload,safeLink,live,type Item} from './model';
import {checkedImage,pngForClipboard} from './media';

const menus=[{name:'เชื่อมต่อ',icon:Link2},{name:'ส่งข้อมูล',icon:Send},{name:'รายการที่ได้รับ',icon:Download},{name:'อุปกรณ์',icon:Monitor},{name:'ประวัติ',icon:History},{name:'ตั้งค่า',icon:Settings}];
const headings=[['เริ่มจากสองเครื่อง.','สร้างห้องบนเครื่องหนึ่ง แล้วเชื่อมต่ออีกเครื่องเข้าด้วยกัน'],['ส่งต่อ แล้วไปต่อ.','ข้อความ ลิงก์ และไฟล์ที่ต้องใช้บนอีกเครื่อง'],['มาถึงแล้ว.','เลือกสิ่งที่ต้องการ แล้วนำไปใช้ต่อ'],['เครื่องที่เชื่อมถึงกัน.','ดูปลายทางก่อนส่งทุกครั้ง'],['ระหว่างห้องนี้.','สถานะการส่งและรับ เก็บชั่วคราวเฉพาะห้องปัจจุบัน'],['ตั้งค่าให้พอดี.','ชื่อเครื่อง ความเป็นส่วนตัว และวิธีใช้งาน']];
const time=(n:number)=>new Date(n).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'});
function countdown(ms:number){const sec=Math.max(0,Math.floor(ms/1000));return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;}

function QR({value}:{value:string}){
  const [image,setImage]=useState(''),[error,setError]=useState(false);
  useEffect(()=>{let active=true;setImage('');setError(false);void QRCode.toDataURL(value,{width:240,margin:2,errorCorrectionLevel:'M',color:{dark:'#29292d',light:'#ffffff'}}).then(url=>{if(active)setImage(url);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[value]);
  return <div className={style.qr}>{image?<img src={image} width={220} height={220} alt="QR คำเชิญสำหรับอีกเครื่อง"/>:<p>{error?'สร้าง QR ไม่สำเร็จ ใช้ลิงก์เชิญแทนได้':'กำลังสร้าง QR…'}</p>}</div>;
}
function Preview({payload}:{payload:Payload}){
  const [url,setURL]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let active=true,revoke='';setURL('');setError('');void checkedImage(payload).then(result=>{revoke=result.url;if(active)setURL(result.url);else URL.revokeObjectURL(result.url);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;if(revoke)URL.revokeObjectURL(revoke);};},[payload]);
  return error?<p className={style.inlineNote}>{error}</p>:url?<img className={style.previewImage} src={url} alt={payload.name}/>:<p>กำลังเตรียมตัวอย่าง…</p>;
}

export default function Workspace(){
  const m=useTransfer();
  const [page,setPage]=useState(0),[code,setCode]=useState(''),[review,setReview]=useState(false),[activeId,setActiveId]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const fileInput=useRef<HTMLInputElement>(null),confirmDialog=useRef<HTMLDialogElement>(null),detailDialog=useRef<HTMLDialogElement>(null);
  const titleRef=useRef<HTMLHeadingElement>(null);
  const [detailMessage,setDetailMessage]=useState('');
  const active=m.items.find(i=>i.id===activeId),s=m.session;
  const destination=m.room?.devices.find(d=>d.role!==s?.role);
  const remaining=s?Math.min(s.deadline-performance.now(),s.wallDeadline-Date.now()):0;
  const inviteRemaining=s?.inviteExpiry?remaining-(s.expiry-s.inviteExpiry)*1000:remaining;
  const showInvite=!!s?.inviteToken&&(s.mode==='legacy'||(!m.room||m.room.pairing==='waiting'))&&inviteRemaining>0;
  const invitation=showInvite&&s?`${location.origin}/try#${new URLSearchParams({...s.mode==='web1'?{v:'web1'}:{},s:s.sid,k:encode(s.secret),t:s.inviteToken!})}`:'';
  const received=m.items.filter(i=>i.direction==='received'),sent=m.items.filter(i=>i.direction==='sent');
  const shown=m.items.filter(i=>(filter==='all'||i.direction===filter)&&`${i.payload.name} ${i.payload.type}`.toLowerCase().includes(query.toLowerCase()));
  const payload=useMemo(()=>m.payload(),[m.file,m.draft,m.kind]);
  const scan=useMemo(()=>scanPayload(payload),[payload]);
  useEffect(()=>{if(review&&s)confirmDialog.current?.showModal();else{confirmDialog.current?.close();if(!s)setReview(false);}},[review,s]);
  useEffect(()=>{setDetailMessage('');if(active)detailDialog.current?.showModal();else detailDialog.current?.close();},[active?.id]);
  useEffect(()=>{if(!s){setCode('');setActiveId('');}},[s]);
  useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});titleRef.current?.focus({preventScroll:true});},[page]);
  async function copyText(value:string){try{await navigator.clipboard.writeText(value);m.setNotice('คัดลอกแล้ว');}catch{m.setError('เบราว์เซอร์ไม่อนุญาตให้คัดลอก เลือกข้อความแล้วคัดลอกเองได้');}}
  function download(id:string){const item=m.available(id);if(!item)return;const url=URL.createObjectURL(new Blob([decode(item.payload.data)],{type:'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download=item.payload.name.replace(/[\\/\x00-\x1f]/g,'_')||'sendviax-file';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setDetailMessage('ส่งไฟล์ให้เบราว์เซอร์ดาวน์โหลดแล้ว');}
  async function copyItem(id:string){const i=m.available(id);if(!i)return;try{
    if(i.payload.type==='text'||i.payload.type==='url'){await navigator.clipboard.writeText(new TextDecoder().decode(decode(i.payload.data)));setDetailMessage('คัดลอกข้อความแล้ว');return;}
    if(typeof ClipboardItem==='undefined'||!navigator.clipboard?.write)throw Error('เบราว์เซอร์นี้ไม่รองรับคัดลอกรูป กรุณาดาวน์โหลดแทน');
    await navigator.clipboard.write([new ClipboardItem({'image/png':pngForClipboard(i.payload,()=>!!m.available(id))})]);setDetailMessage('คัดลอกรูปแล้ว วางในแอปที่รองรับได้เลย');
  }catch(e){setDetailMessage((e as Error).message||'คัดลอกไม่สำเร็จ กรุณาดาวน์โหลดแทน');}}
  function startReview(){if(!m.ready){m.setError('เชื่อมต่อและยืนยันเครื่องก่อนส่ง');return;}if(!m.file&&!m.draft.trim()){m.setError('กรอกข้อความหรือเลือกไฟล์ก่อน');return;}if(decode(payload.data).length>LIMIT){m.setError('ข้อมูลต้องไม่เกิน 5 MiB');return;}setReview(true);}
  function status(i:Item){return i.direction==='received'?'ได้รับแล้ว':s?.mode==='legacy'&&i.status==='available'?'อัปโหลดแล้ว':statuses[i.status];}
  function table(list:Item[]){return list.length?<div className="table-wrap"><table><thead><tr><th>รายการ</th><th>ชนิด</th><th>ขนาด</th><th>เวลา</th><th>สถานะ</th></tr></thead><tbody>{list.map(i=><tr key={i.id}><td><button className="table-link" onClick={()=>setActiveId(i.id)}>{i.payload.name}</button></td><td>{labels[i.payload.type]}</td><td>{size(i.size)}</td><td>{time(i.time)}</td><td><span className={i.status==='completed'?'badge':style.statusNeutral}>{status(i)}</span></td></tr>)}</tbody></table></div>:<div className="empty"><History size={32}/><h3>ยังไม่มีรายการ</h3><p>รายการจะปรากฏที่นี่เมื่อส่งหรือรับข้อมูล</p></div>;}
  const nameField=<label className={style.field}>ชื่อเครื่องนี้<input value={m.name} onChange={e=>m.setName(e.target.value)} maxLength={40} placeholder="เช่น MacBook ของฉัน" autoComplete="off"/></label>;
  const pairing=<section className={`card ${style.pairing}`}>
    <div className="section-heading"><div><span className="eyebrow">PRIVATE SESSION</span><h2>{!s?'เชื่อมต่ออีกเครื่อง':m.ready?'พร้อมส่งต่อถึงกัน':s.role==='owner'?'ชวนอีกเครื่องเข้าห้อง':'ยืนยันว่าเป็นเครื่องของคุณ'}</h2></div><span className="icon-tile"><Link2 size={22}/></span></div>
    {!s?<>
      {nameField}
      <div className={style.connectChoices}><div><h3>เริ่มห้องใหม่</h3><p>สร้าง QR และลิงก์สำหรับเว็บบนอีกเครื่อง ใช้ได้ครั้งเดียว</p><button className="primary" disabled={!!m.busy||!m.name.trim()} onClick={()=>void m.create()}><Link2 size={16}/>สร้างห้องใหม่</button></div><div><h3>มีลิงก์เชิญแล้ว</h3><p>วางลิงก์ที่ได้รับ หรือสแกน QR ด้วยกล้องมือถือ</p><label className={style.field}>ลิงก์เชิญ<input type="password" value={m.joinedLink} onChange={e=>m.setJoinedLink(e.target.value)} autoComplete="off" placeholder="วางลิงก์เชิญที่นี่"/></label><button disabled={!!m.busy||!m.joinedLink.trim()||!m.name.trim()} onClick={()=>void m.join(m.joinedLink)}>เข้าร่วมด้วยลิงก์ <ArrowRight size={15}/></button></div></div>
      <details className={style.legacy}><summary>เชื่อมกับแอป Android / iOS รุ่นเดิม</summary><p>ใช้ห้องรุ่นเดิมเพื่อส่งกับแอปที่ยังไม่รองรับการยืนยันรหัส ลิงก์ใช้ซ้ำได้ และยังไม่มีรายชื่อเครื่องหรือใบยืนยันการรับ</p><button disabled={!!m.busy||!m.name.trim()} onClick={()=>void m.create(true)}>สร้างห้องสำหรับแอปรุ่นเดิม</button></details>
    </>:<>
      <div className={style.roomLine}><span>ห้อง {s.sid.slice(0,8)} · {s.role==='owner'?'ผู้สร้าง':'ผู้เข้าร่วม'}</span><span><Clock size={14}/>เหลือ {countdown(remaining)}</span></div>
      {showInvite&&<div className={style.inviteGrid}><QR value={invitation}/><div><h3>{s.mode==='web1'?'สแกน แล้วบอกรหัสกลับมา':'เปิดลิงก์ในแอปรุ่นเดิม'}</h3><p>เปิด QR ด้วยกล้องอีกเครื่อง หรือส่งลิงก์ให้เฉพาะเครื่องที่ต้องการเชื่อมต่อ</p><button className="primary" onClick={()=>void copyText(invitation)}><Copy size={15}/>คัดลอกลิงก์เชิญ</button><p className={style.inlineNote}>{s.mode==='web1'?`คำเชิญเหลือ ${countdown(inviteRemaining)} · ใช้ได้หนึ่งเครื่อง`:'โหมดเข้ากันได้กับแอปรุ่นเดิม · ไม่มีขั้นยืนยันรหัส'}</p></div></div>}
      {s.mode==='web1'&&!m.ready&&m.room?.pairing==='pending'&&(s.role==='owner'?<div className={style.verification}><span className="eyebrow">CONFIRM DEVICE</span><h3>{destination?.name||'อีกเครื่อง'} ขอเข้าร่วม</h3><p>ขอรหัส 6 หลักจากหน้าจอเครื่องรับ แล้วกรอกด้านล่างเพื่ออนุญาตให้ส่งข้อมูล</p><label className={style.field}>รหัสจากเครื่องรับ<input className={style.codeInput} inputMode="numeric" autoComplete="off" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label><button className="primary" disabled={!!m.busy||code.length!==6} onClick={()=>void m.confirm(code)}><Check size={16}/>ยืนยันเครื่องนี้</button><p className={style.inlineNote}>ไม่ใช่เครื่องที่ต้องการ? ปิดห้องแล้วสร้างคำเชิญใหม่</p></div>:<div className={style.verification}><p>บอกรหัสนี้ให้เจ้าของห้องกรอกบนอีกเครื่อง</p><strong className={style.codeDisplay}>{s.code}</strong><p>รอเจ้าของห้องยืนยัน · ยังส่งข้อมูลไม่ได้</p></div>)}
      {s.mode==='web1'&&!m.ready&&inviteRemaining<=0&&<p className="warning">คำเชิญหมดอายุแล้ว ปิดห้องแล้วสร้างใหม่เพื่อเชื่อมต่อ</p>}
      {m.ready&&<div className={style.connectedPanel}><span className={style.successIcon}><Check size={23}/></span><div><h3>{s.mode==='web1'?`เชื่อมต่อกับ ${destination?.name||'อีกเครื่อง'}`:'ห้องรุ่นเดิมพร้อมส่ง'}</h3><p>{s.mode==='web1'?'ยืนยันคู่แล้ว · เนื้อหาเข้ารหัสก่อนออกจากเครื่อง':'ให้เปิดห้องไว้ทั้งสองเครื่องเพื่อรับข้อมูล'}</p></div><button className="primary" onClick={()=>setPage(1)}>เริ่มส่ง <ArrowUpRight size={15}/></button></div>}
      <div className={style.roomActions}><button className="danger" disabled={!!m.busy} onClick={()=>void m.close()}><LogOut size={15}/>{s.mode==='web1'||s.role==='owner'?'ปิดห้องและตัดการเชื่อมต่อ':'ออกจากห้อง'}</button><span>รีเฟรชหน้านี้แล้วต้องเชื่อมต่อใหม่</span></div>
    </>}
  </section>;
  return <div className={`shell ${style.workspace}`}><aside><Link className="brand" href="/"><img src="/brand/sendviax.png" width={48} height={48} alt=""/>Sendviax</Link><nav aria-label="เมนูใช้งาน">{menus.map((entry,i)=><button key={entry.name} className={page===i?'selected':''} aria-current={page===i?'page':undefined} onClick={()=>setPage(i)}><entry.icon size={18}/>{entry.name}{i===2&&received.length>0&&<span className={style.count}>{received.length}</span>}</button>)}</nav><div className="sidebar-bottom"><span className="avatar"><ShieldCheck size={17}/></span><div>ห้องชั่วคราว<small>ข้อมูลอยู่ในห้องนี้เท่านั้น</small></div></div></aside>
    <main><header><div className={style.pageTitle}><span>SENDVIAX / WORKSPACE</span><h1 ref={titleRef} tabIndex={-1}>{headings[page][0]}</h1><p>{headings[page][1]}</p></div><span className={`connection ${m.healthy?'online':''}`}><Wifi size={13}/>{m.healthy?'ติดต่อ Relay ได้':'กำลังเชื่อมต่อ Relay'}</span></header>
    <div className="content">
      {m.error&&<div className={style.error} role="alert"><p>{m.error}</p><button aria-label="ปิดข้อผิดพลาด" onClick={()=>m.setError('')}><X size={16}/></button></div>}
      {m.notice&&<div className={style.notice} role="status"><Check size={15}/><span>{m.notice}</span><button aria-label="ปิดข้อความ" onClick={()=>m.setNotice('')}><X size={14}/></button></div>}
      {m.busy&&<p className={style.working} role="status">{m.busy}…</p>}
      {page===0&&<><div className={style.journey}>{['สร้างหรือเข้าห้อง','ยืนยันอีกเครื่อง','ส่งและรับข้อมูล'].map((label,i)=><div key={label} className={(i===0&&!s||i===1&&s&&!m.ready||i===2&&m.ready)?style.currentStep:''}><span>{i+1}</span>{label}{i<2&&<ChevronRight size={14}/>}</div>)}</div>{pairing}<div className={style.explainer}><ShieldCheck size={21}/><div><h3>ใช้เสร็จ แล้วปิดห้องได้เลย</h3><p>ห้องมีอายุ 15 นาที รายการมีอายุไม่เกิน 5 นาที ลิงก์เชิญมีสิทธิ์เข้าห้อง โปรดส่งให้เฉพาะคนที่ไว้ใจ</p></div></div></>}
      {page===1&&<>{!m.ready&&pairing}<section className={`card ${style.composer}`}><div className={style.composerHeading}><h2>ส่งอะไรดี?</h2><span>ครั้งละหนึ่งรายการ · สูงสุด 5 MiB</span></div><div className={style.typeSwitch}><button className={!m.file&&m.kind==='text'?'chosen':''} onClick={()=>{m.removeFile();m.setKind('text');}}><FileText size={15}/>ข้อความ / โค้ด</button><button className={!m.file&&m.kind==='url'?'chosen':''} onClick={()=>{m.removeFile();m.setKind('url');}}><Link2 size={15}/>ลิงก์</button><button className={m.file?'chosen':''} onClick={()=>fileInput.current?.click()}><UploadCloud size={15}/>รูปภาพ / ไฟล์</button></div>
        {m.file?<div className={style.selectedFile}>{m.file.type==='image'?<Preview payload={m.file}/>:<FileText size={40}/>}<div><h3>{m.file.name}</h3><p>{size(decode(m.file.data).length)} · {m.file.mime}</p></div><button aria-label="นำไฟล์ออก" onClick={m.removeFile}><X size={17}/></button></div>:<label className={style.field}>{m.kind==='url'?'ลิงก์ที่ต้องการส่ง':'ข้อความที่ต้องการส่ง'}<textarea value={m.draft} onChange={e=>m.setDraft(e.target.value)} placeholder={m.kind==='url'?'https://…':'พิมพ์หรือวางข้อความ โค้ด หรือโน้ตไว้ตรงนี้'} spellCheck={false}/></label>}
        <div className={`drop ${style.smallDrop}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files.length>1)m.setNotice('รุ่นนี้ส่งทีละไฟล์ เลือกไฟล์แรกให้แล้ว');void m.pick(e.dataTransfer.files[0]);}}><UploadCloud size={25}/><p>ลากรูปหรือไฟล์มาวาง หรือ <button className="text-button" onClick={()=>fileInput.current?.click()}>เลือกจากเครื่อง</button></p><small>PDF และเสียงส่งเป็นไฟล์ได้</small></div><input ref={fileInput} type="file" hidden onChange={e=>{void m.pick(e.target.files?.[0]);e.target.value='';}}/>
        <div className="destination"><Monitor size={22}/><div><b>ปลายทาง: {m.ready?(destination?.name||'อีกฝั่งในห้องรุ่นเดิม'):'ยังไม่ได้ยืนยันเครื่อง'}</b><p>{destination?`${destination.platform} · ${destination.online&&m.healthy?'ติดต่อได้ล่าสุด':'ยังไม่พบการตอบกลับล่าสุด'}`:'ไปหน้าเชื่อมต่อเพื่อดูรายละเอียดห้อง'}</p></div></div><button className="primary full" disabled={!m.ready||!!m.busy||(!m.file&&!m.draft.trim())} onClick={startReview}><Send size={16}/>ตรวจสอบและส่ง</button></section></>}
      {page===2&&<><div className="section-heading"><p>{received.length} รายการพร้อมใช้ · หมดอายุอัตโนมัติ</p><button disabled={!received.length} onClick={m.clearReceived}><X size={15}/>ล้างรายการที่ได้รับ</button></div>{received.length?<div className={style.inboxList}>{received.map(i=><button key={i.id} className={style.inboxRow} onClick={()=>setActiveId(i.id)}><span className="icon-tile">{i.payload.type==='image'?<ImageIcon size={22}/>:<FileText size={22}/>}</span><span><b>{i.payload.name}</b><small>{labels[i.payload.type]} · {size(i.size)} · {time(i.time)}</small>{(i.payload.type==='text'||i.payload.type==='url')&&<p>{new TextDecoder().decode(decode(i.payload.data)).slice(0,100)}</p>}</span><ChevronRight size={17}/></button>)}</div>:<section className="card empty"><Download size={35}/><h2>รอสิ่งที่อีกเครื่องส่งมา</h2><p>เปิดห้องนี้ค้างไว้ รายการใหม่จะปรากฏอัตโนมัติ</p><button onClick={()=>setPage(s?1:0)}>{s?'ลองส่งข้อมูล':'ไปเชื่อมต่อ'}</button></section>}</>}
      {page===3&&<>{!s?pairing:s.mode==='legacy'?<section className="card"><h2>ห้องสำหรับแอปรุ่นเดิม</h2><p>เชื่อมต่อห้องแล้ว แต่รุ่นนี้ไม่มีชื่อเครื่องหรือสถานะออนไลน์ของอีกฝั่ง ลองส่งข้อความกลับมาเพื่อยืนยันการเชื่อมต่อ</p><button onClick={()=>setPage(1)}>ลองส่งข้อมูล <ArrowRight size={15}/></button></section>:<><div className={style.devicePair}>{(m.room?.devices||[]).map(d=><section key={d.role} className={`card ${style.deviceCard}`}><span className="eyebrow">{d.role===s.role?'เครื่องนี้':'ปลายทาง'}</span><div className={style.deviceIllustration}><Monitor size={54}/></div><h2>{d.name}</h2><p>{d.platform}</p><span className={d.online&&m.healthy?'badge':style.statusNeutral}>{d.online&&m.healthy?'ติดต่อได้ใน 12 วินาทีล่าสุด':'ขาดการติดต่อชั่วคราว'}</span><p className={style.inlineNote}>ชื่อและระบบที่เครื่องนั้นแจ้ง ไม่ใช่การยืนยันตัวตน</p></section>)}</div>{m.room?.devices.length===1&&<p className="note">ยังไม่มีอีกเครื่องเข้าร่วม เปิดหน้าเชื่อมต่อเพื่อส่งคำเชิญ</p>}<section className="card">{nameField}<div className="actions"><button disabled={!!m.busy||!m.name.trim()} onClick={()=>void m.rename()}>บันทึกชื่อเครื่องนี้</button><button className="danger" disabled={!!m.busy} onClick={()=>void m.close()}>ตัดการเชื่อมต่อทั้งสองเครื่อง</button></div></section></>}</>}
      {page===4&&<><section className="card"><div className={style.historyControls}><label className={style.search}><Search size={16}/><input aria-label="ค้นหาประวัติ" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่อรายการ…"/></label><div className="actions">{[['all','ทั้งหมด'],['sent','ส่ง'],['received','รับ']].map(([value,label])=><button key={value} className={filter===value?'chosen':''} onClick={()=>setFilter(value)}>{label}</button>)}</div></div>{table(shown)}</section>{!!m.room?.receipts.length&&<section className="card"><h2>ใบยืนยันจากผู้รับ</h2><p>“ผู้รับรับแล้ว” หมายถึงเครื่องรับรายงานว่ารับและถอดรหัสแล้ว ยังไม่ได้หมายความว่าผู้ใช้เปิดหรือวางข้อมูล</p><div className={style.receipts}>{m.room.receipts.map(r=><div key={r.id}><code>{r.id.slice(0,8)}</code><span>{statuses[r.status]}</span><small>{r.completed_at?time(r.completed_at*1000):'—'}</small></div>)}</div></section>}<p className="note">เนื้อหาหมดอายุแล้วจะหายจากรายการ ใบยืนยันเหลือเฉพาะรหัสและสถานะจนปิดห้อง</p></>}
      {page===5&&<><section className="card"><h2>ห้องและความเป็นส่วนตัว</h2>{[['อายุห้อง','15 นาที'],['อายุคำเชิญแบบใหม่','5 นาที · รับได้หนึ่งเครื่อง'],['อายุรายการ','ไม่เกิน 5 นาที และไม่เกินอายุห้อง'],['ข้อมูลชั่วคราวบนเว็บ','สูงสุด 20 รายการ / 20 MiB ในหน่วยความจำ'],['ขนาดต่อรายการ','5 MiB'],['ประวัติถาวร','ยังไม่เปิดใช้'],['การเชื่อมต่อ','Relay · ยังไม่มี P2P'],['การตรวจข้อมูล','ตรวจข้อความด้วยกฎบนเครื่อง ไม่ตรวจ OCR / เนื้อหา PDF']].map(([label,value])=><div className="setting" key={label}><b>{label}</b><span>{value}</span></div>)}<p className="note">ปิดห้องหรือหมดอายุแล้วล้างข้อมูลที่เว็บถืออยู่ แต่เรียกคืนข้อมูลที่คัดลอกหรือดาวน์โหลดไปแล้วไม่ได้</p><div className={style.roomActions}><button disabled={!s||!!m.busy} className="danger" onClick={()=>void m.close()}>ปิดห้องและล้างข้อมูล</button><button disabled={!s} onClick={m.localExit}>ล้างบนเครื่องนี้เมื่อออฟไลน์</button></div></section><section className="card"><h2>นำข้อมูลไปใช้ต่อ</h2><p>ข้อความกดคัดลอกได้ รูปกดคัดลอกได้ในเบราว์เซอร์ที่รองรับ ส่วน PDF เสียง และไฟล์ทั่วไปกดดาวน์โหลดแล้วเปิดจากเครื่อง ไม่มีการอ่านคลิปบอร์ดเบื้องหลัง</p><Link className={style.inlineLink} href="/download">ดูแอปสำหรับแต่ละระบบ <ArrowUpRight size={15}/></Link></section></>}
      <footer><ShieldCheck size={13}/>เข้ารหัสก่อนส่ง · ห้องชั่วคราว · รุ่นทดลอง ใช้ข้อมูลสังเคราะห์</footer>
    </div></main>
    <dialog ref={confirmDialog} onCancel={()=>setReview(false)}><div className="modal-title"><span className="icon-tile"><ShieldCheck size={22}/></span><div><h2>ตรวจสอบก่อนส่ง</h2><p>ข้อมูลจะถูกเข้ารหัสบนเครื่องนี้</p></div><button className="round" aria-label="ปิดการยืนยัน" onClick={()=>setReview(false)}><X size={18}/></button></div><div className="detail-meta modal-meta"><div><small>รายการ</small><b>{payload.name}</b></div><div><small>ปลายทาง</small><b>{destination?.name||'อีกฝั่งในห้อง'}</b></div><div><small>ชนิด</small><b>{labels[payload.type]}</b></div><div><small>ขนาด</small><b>{size(decode(payload.data).length)}</b></div></div>{payload.type==='text'||payload.type==='url'?<pre>{new TextDecoder().decode(decode(payload.data)).slice(0,2000)}</pre>:payload.type==='image'?<Preview payload={payload}/>:null}<p className="warning">{scan.message}</p><div className="actions"><button className="grow" onClick={()=>setReview(false)}>กลับไปแก้ไข</button><button className="primary grow" disabled={!!m.busy||!m.ready} onClick={()=>{setReview(false);void m.send();}}>ยืนยันการส่ง <Send size={15}/></button></div></dialog>
    <dialog ref={detailDialog} onCancel={()=>setActiveId('')}>{active&&<><div className="modal-title"><span className="icon-tile"><Download size={22}/></span><div><h2>{active.payload.name}</h2><p>{labels[active.payload.type]} · {size(active.size)}</p></div><button className="round" aria-label="ปิดรายละเอียด" onClick={()=>setActiveId('')}><X size={18}/></button></div>{active.payload.type==='image'?<Preview payload={active.payload}/>:active.payload.type==='text'||active.payload.type==='url'?<pre>{new TextDecoder().decode(decode(active.payload.data))}</pre>:<div className="empty"><FileText size={36}/><p>ดาวน์โหลดแล้วเปิดด้วยแอปที่รองรับ</p></div>}<div className="actions">{['text','url','image'].includes(active.payload.type)&&<button className="primary" onClick={()=>void copyItem(active.id)}><Copy size={15}/>{active.payload.type==='image'?'คัดลอกรูป':'คัดลอกข้อความ'}</button>}<button onClick={()=>download(active.id)}><Download size={15}/>ดาวน์โหลด</button>{safeLink(active.payload)&&<a className={style.inlineLink} href={safeLink(active.payload)!} target="_blank" rel="noopener noreferrer" onClick={e=>{if(!m.available(active.id))e.preventDefault();}}>เปิดลิงก์ <ArrowUpRight size={15}/></a>}</div>{detailMessage&&<p role="status" className={style.inlineNote}>{detailMessage}</p>}<details className="hash"><summary>ตรวจ SHA-256</summary><code>{active.hash}</code><p>ใช้เปรียบเทียบกับเครื่องส่ง การตรวจความถูกต้องขณะถอดรหัสใช้ AES-GCM</p></details><p className={style.inlineNote}>รายการนี้เหลือ {countdown(Math.min(active.deadline-performance.now(),active.wallDeadline-Date.now()))}</p></>}</dialog>
  </div>;
}
